### ISSUE TITLE
How to set cover image & each chapter's title

### ISSUE THREAD

**Issue by bonfy** [lepture/getbook#2]
can you give a demo how to set the cover image? 
If it can set the chapter title by myself I think would be better.

**Comment by lepture** [comment]
Get help information:

```
getbook -h
```

Generate cover with:

```
getbook -c "image url"
```

---

You need to configure fonts to generate cover. Check it here: https://github.com/lepture/getbook/blob/master/getbook/cli.py#L25

**Comment by bonfy** [comment]
ok Thanks
