### ISSUE TITLE
Error: The combinator '>' at postion 0, must have a selector before it

### ISSUE THREAD

**Issue by lzwjava** [lepture/getbook#5]
https://github.com/lepture/getbook/blob/e39e0668ea1cf0e50f1ba6ca6cbd2d73e4cb13a1/getbook/core/parse_content.py#L137-L139

Error: SelectorSyntaxError("The combinator '>' at postion 0, must have a selector before it\n  line 1:\n> p\n^")

My Environment:

When I type Ctrl+C to cancel the program, it shows:

```
  File "/usr/local/lib/python3.9/site-packages/getbook/cli.py", line 140, in main
    bg.build(book, force=args.force, epub=args.epub, mobi=args.mobi)
  File "/usr/local/lib/python3.9/site-packages/getbook/gen.py", line 48, in build
    self._write_chapter(book, force=force, builder=builder)
  File "/usr/local/lib/python3.9/site-packages/getbook/gen.py", line 103, in _write_chapter
    chapter_index = _parse_chapter(c, chapter_index)
```

Serveral months before, there are no problem here. So may be I use python 3.9 to cause this problem.

I just record this issue here. It may help.

**Comment by lzwjava** [comment]
https://github.com/facelessuser/soupsieve/issues/110

```python
    p_count = len(el.select(':scope > p'))
```

When the line changes to the above line, it works again.

**Comment by lepture** [comment]
@lzwjava can you submit a PR?

**Comment by lzwjava** [comment]
https://github.com/lepture/getbook/pull/7

ok
